server:
  port: 8082

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/spring_database}
    username: postgres
    password: rootroot
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update