server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/first_controlwork
    username: postgres
    password: rootroot
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  security:
    user:
      password: 1234
jwt:
  secret:
    access: and0LnNlY3JldC5hY2Nlc3Muand0LnNlY3JldC5hY2Nlc3M=
    refresh: refresh=and0LnNlY3JldC5yZWZyZXNoLmp3dC5zZWNyZXQucmVmcmVzaA==
